export default {
  products: [
    {
      id: 1,
      name: "T-Shirt",
      price: "$65",
      brand: "Nike",
      category: "T-Shirts",
      rating: 4.3,
      numrating: 46,
      image: "/images/amazon.jpg",
    },
    {
      id: 2,
      name: "T-Shirt",
      price: "$65",
      brand: "Nike",
      category: "T-Shirts",
      rating: 4.3,
      numrating: 46,
      image: "/images/amazon.jpg",
    },
    {
      id: 3,
      name: "T-Shirt",
      price: "$65",
      brand: "Nike",
      category: "T-Shirts",
      rating: 4.3,
      numrating: 46,
      image: "/images/amazon.jpg",
    },
    {
      id: 4,
      name: "T-Shirt",
      price: "$65",
      brand: "Nike",
      category: "T-Shirts",
      rating: 4.3,
      numrating: 46,
      image: "/images/amazon.jpg",
    },
    {
      id: 5,
      name: "T-Shirt",
      price: "$65",
      brand: "Nike",
      category: "T-Shirts",
      rating: 4.3,
      numrating: 46,
      image: "/images/amazon.jpg",
    },
    {
      id: 6,
      name: "T-Shirt",
      price: "$65",
      brand: "Nike",
      category: "T-Shirts",
      rating: 4.3,
      numrating: 46,
      image: "/images/amazon.jpg",
    },
    {
      id: 7,
      name: "T-Shirt",
      price: "$65",
      brand: "Nike",
      category: "T-Shirts",
      rating: 4.3,
      numrating: 46,
      image: "/images/amazon.jpg",
    },
    {
      id: 8,
      name: "T-Shirt",
      price: "$65",
      brand: "Nike",
      category: "T-Shirts",
      rating: 4.3,
      numrating: 46,
      image: "/images/amazon.jpg",
    },
  ],
};
